---
- name: Migrating DB
  copy:
    src: "{{ item }}"
    dest: /var/lib/mongodb
    mode: 755
  with_fileglob:
    - "{{ role_path }}/dist/db/*"

- name: Create Keystone directory
  file:
    path: /var/www/admin.volvovalor.com/html
    state: directory

- name: Deploying Keystone Backend
  copy:
    src: "{{ item }}"
    dest: /var/www/admin.volvovalor.com/html
    mode: 755
  with_fileglob:
    - "{{ role_path }}/dist/admin.volvovalor.com/*"

#- name: Deploying Angular Frontend
#  copy:
#    src: "{{ item }}"
#    dest: /var/www/volvovalor.com/html
#    mode: 644
#  with_fileglob:
#    - {{ role_path }}/dist/volvovalor.com/*

- name: Push server block configuration
  copy:
    src: "{{ role_path }}/static-files/admin.volvovalor.com"
    dest: /etc/nginx/sites-available
    mode: 755

- name: Create admin.volvovalor.com directory
  file:
    path: /etc/nginx/sites-enabled/admin.volvovalor.com
    state: directory

- name: Create symlink to admin.volvovalor.com
  file:
    src: /etc/nginx/sites-available/admin.volvovalor.com
    dest: /etc/nginx/sites-enabled/admin.volvovalor.com
    state: link
    force: true
  notify: nginx reload

- name: Restart
  service:
    name: mongodb
    state: reloaded
