---
# ANSIBLE PLAY (Group of tasks that are performed on a certain set of hosts)
- hosts: hosts
  tasks:
    - name: Installs nginx web server
      # Update package cache and then install nginx
      apt: pkg=nginx state=installed update_cache=true
      notify:
        # Notify start nginx handler - starts nginx after it's installed
        # Only triggers when something is changed
        - start nginx

    - name: Upload default index.php
      # Replace default index.php file with static resource
      copy: src=static-files/index.php dest=/usr/share/nginx/www/ mode=0644
      # Log if action was succesful
      register: php
      # Ignore errors to prevent play from aborting
      ignore_errors: True

      # Remove index.html if transfer was succesful
    - name: Remove index.html from host
      command: rm /usr/share/nginx/www/index.html
      when: php|success

      # Upload index.html if transfer failed
    - name: Upload default index.html
      copy: src=static-files/index.html dest=/usr/share/nginx/www/ mode=0644
      when: php|failed

  handlers:
    - name: start nginx
      service: name=nginx state=started
