---
- name: Get installation script
  get_url:
    url: "http://deb.nodesource.com/setup_6.x"
    dest: "{{ temp_folder }}/nodejs.sh"

- name: Set execution right to script
  file:
    path: "{{ temp_folder }}/nodejs.sh"
    mode: "u+x"

- name: Execution installation script
  shell: "{{ temp_folder }}/nodejs.sh"

- name: Remove installation script
  file:
    path: "{{ temp_folder }}/nodejs.sh"
    state: absent

- name: Install Node.js
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - nodejs

- name: Install bower and gulp globally
  npm: name={{ item }} state=present global=yes
  with_items:
    - bower
    - gulp

- name: Upload default app.js
  copy: src=static-files/app.js dest=/home/pi/dev/node/ mode=0644

- name: Install pm2
  npm: name=pm2 global=yes production=yes

- name: Start app
  command: pm2 start app.js --name app chdir=/home/pi/dev/node
  ignore_errors: yes
  #when: npm_finished.changed
